#! ./venv/bin/python3

import traceback
import sys

# improve by using some dynamic solution offered e.g. here:
# https://stackoverflow.com/questions/1057431/loading-all-modules-in-a-folder-in-python/20753073#20753073
from checks import *

checks = []
tbs = []


def run_check(check, conf):
  global checks
  checks.append(check)

  try:
    check(conf)
  except AssertionError:
    _, _, tb = sys.exc_info()
    global tbs
    tbs.append(tb)


def run_checks(conf):
  errors = 0

  run_check(area_teaser_options_placement_VF_7149.check, conf)
  run_check(ece_admin.check, conf)

  print_results(checks, tbs)

  if len(tbs) > 0:
    for tb in tbs:
      traceback.print_tb(tb)


def print_results(checks, tbs):
  print(
    "Tests: " + str(len(checks)) +
    " Successes: " + str(len(checks) - len(tbs)) +
    " Errors: " + str(len(tbs))
  )


def read_user_conf():
  conf = {
    "ece_admin_url": "http://localhost:8080/escenic-admin",
    "ws_base_url": "http://localhost:8080/webservice",
    "publication": "rohan",
    "user": "rohan_admin",
    "password": "admin"
  }

  return conf

if __name__ == "__main__":
  conf = read_user_conf()
  run_checks(conf)
